services:
  mongodb-auth:
    image: mongo:latest
    container_name: mongodb-auth
    restart: no
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - "27017:27017"
    volumes:
      - mongodb_auth_data:/data/db
    networks:
      - event-network

  mongodb-event:
    image: mongo:latest
    container_name: mongodb-event
    restart: no
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - "27018:27017"
    volumes:
      - mongodb_event_data:/data/db
    networks:
      - event-network

  rabbitmq:
    image: rabbitmq:3-management  # 관리 GUI가 포함된 이미지
    container_name: rabbitmq
    ports:
      - "5672:5672"  # AMQP 프로토콜 포트
      - "15672:15672"  # 관리 UI 포트
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - event-network

  gateway-server:
    build:
      context: ./gateway-server
      dockerfile: Dockerfile
#      target: development
    command: npm run start:dev
    container_name: gateway-server
    restart: no
    ports:
      - "3004:3004"
#    volumes:
##      - .:/var/app
#      - ./gateway-server:/var/app  # 로컬 코드를 컨테이너 내부로 마운트
##      - var/app/node_modules      # node_modules는 컨테이너 내부 것 사용
    env_file:
      - /gateway-server/.env.docker
    depends_on:
      - rabbitmq
      - mongodb-auth
      - mongodb-event
    networks:
      - event-network

  auth-server:
    build:
      context: ./auth-server
      dockerfile: Dockerfile
#      target: development
    command: npm run start:dev
    container_name: auth-server
    restart: no
    ports:
      - "3001:3001"
#    volumes:
##      - .:/var/app
#      - ./auth-server:/var/app  # 로컬 코드를 컨테이너 내부로 마운트
##      - var/app/node_modules      # node_modules는 컨테이너 내부 것 사용
    env_file:
      - /auth-server/.env.docker
    depends_on:
      - rabbitmq
      - mongodb-auth
    networks:
      - event-network

  event-server:
    build:
      context: ./event-server
      dockerfile: Dockerfile
#      target: development
    command: npm run start:dev
    container_name: event-server
    restart: no
    ports:
      - "3002:3002"
#    volumes:
#      - ./event-server:/var/app
    env_file:
      - /event-server/.env.docker
    depends_on:
      - rabbitmq
      - mongodb-event
    networks:
      - event-network

networks:
  event-network:
    driver: bridge

volumes:
  mongodb_auth_data:
  mongodb_event_data:

