services:
  e2e:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./specs:/var/app/specs
    depends_on:
      - mongodb-auth
      - mongodb-event
      - rabbitmq
      - gateway-server
      - auth-server
      - event-server
    networks:
      - event-network

  mongodb-auth:
    image: mongo:latest
    container_name: mongodb-auth-e2e
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - "27017:27017"
    volumes:
      - mongodb_auth_data:/data/db
    networks:
      - event-network

  mongodb-event:
    image: mongo:latest
    container_name: mongodb-event-e2e
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - "27018:27017"
    volumes:
      - mongodb_event_data:/data/db
    networks:
      - event-network

  rabbitmq:
    image: rabbitmq:3-management  # 관리 GUI가 포함된 이미지
    container_name: rabbitmq-e2e
    ports:
      - "5672:5672"  # AMQP 프로토콜 포트
      - "15672:15672"  # 관리 UI 포트
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - event-network

  gateway-server:
    build:
      context: ../gateway-server
      dockerfile: Dockerfile
    container_name: gateway-server-e2e
    restart: no
    ports:
      - "3004:3004"
    env_file:
      - ../gateway-server/.env.docker
    depends_on:
      - mongodb-auth
      - mongodb-event
      - rabbitmq
    networks:
      - event-network

  auth-server:
    build:
      context: ../auth-server
      dockerfile: Dockerfile
    container_name: auth-server-e2e
    restart: no
    ports:
      - "3001:3001"
    env_file:
      - ../auth-server/.env.docker
    depends_on:
      - mongodb-auth
      - rabbitmq
    networks:
      - event-network

  event-server:
    build:
      context: ../event-server
      dockerfile: Dockerfile
    container_name: event-server-e2e
    restart: no
    ports:
      - "3002:3002"
    env_file:
      - ../event-server/.env.docker
    depends_on:
      - mongodb-event
      - rabbitmq
    networks:
      - event-network

networks:
  event-network:
    driver: bridge

volumes:
  mongodb_auth_data:
  mongodb_event_data: